services:
  wa-bot:
    build: .
    container_name: wa-ping-bot-v2
    restart: unless-stopped
    ports:
      - 6800:6800
    environment:
      API_HOST: "${API_HOST:-http://host.docker.internal:3000}"
    volumes:
      - ./data:/app/data
    tty: true
